name = "pinecone-demo"
main = "src/worker.ts"
compatibility_date = "2023-06-28"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
PINECONE_ENVIRONMENT = "us-west1-gcp-free"
